---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs/content
  label: Pages
  create: all
  match: "*"
upload_dir: docs/img
public_path: docs/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
